### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by gabriellet** [ThePhD/lepix#15]
We need to use the C code in commits ad02f05, cd6f557, and f9e1a85 and make it analogous to our example in parallel.lepix. Once this is done we can examine the LLVM IR output of the C program and use this to see what our compiler should be generating for the Lepix equivalent.

**Comment by gabriellet** [comment]
Other issues: the C code needs to be able to work for arrays where the size is specified at compile time and also arrays where the size is specified at runtime.

**Comment by gabriellet** [comment]
This [website](https://www.objc.io/issues/6-build-tools/compiler/) was super useful because for a while I could not get the LLVM byte code into a human readable version using apple's proprietary clang. It doesn't have the LLVM-dis tool installed (it seemed I needed this from [this website](http://www.isi.edu/~pedro/Teaching/CSCI565-Spring15/Projects/Project1-LLVM/LLVMInstructions-MacOSX10.9.pdf) and it wasn't clear how to install this without screwing up the clang installation. However it turns out you can actually directly emit LLVM IR (wasn't clear from the first set of instructions) from clang like this:

`clang -emit-llvm -O0 -S -c threaded.c -o threaded.ll`

On my linux machine I did

```
clang -emit-llvm -O0 -c threaded.c -o threaded.bc
llvm-dis -f threaded.bc
```

and that worked too.

**Comment by gabriellet** [comment]
So I was looking at our parallel.lepix program, and I noticed a few things. 

```
fun main () : int {
    var values : int[] = [
        1, 2, 
        1, 2,
        1, 2, 
        1, 2
    ];
    int sum = 0;
    parallel {
        var size : int = values.size() / lang.thread_count;
        for (var x : int = 0 to size) {
            var i : int = x + (lang.thread_index * size);
            atomic {
                sum = sum + values[i];
            }
        }
    }
    // sum == 12
    return sum;
}
```
1. `lang.thread_count`: we decided that we would not permit more than a particular number of threads? I don't remember the justification of this. Is this number of threads 4? If so I'm going to hard code this into our C examples.
2. This example has an array which is declared and initialized at compile time. One of the things that Edwards said we should do is have dynamically sized arrays. What does that look like in lepix?
3. How exactly does this `size()` method work? It's hard to do this in C without having compile time constants.
4. I'm assuming our `parallel` and `atomic` blocks take care of thread and mutex creation and destruction respectively. Just a couple comments on this:
   - The `parallel` block needs to create and initialize threads (`pthread_t threads[NTHREADS];`), thread numbers (`thread_nums[NTHREADS];`)
   - It then needs to pass each thread the actual work (`do_work()` in the C code) and its thread number, something like this 
   
   ```
   for (i = 0; i < NTHREADS; i++) {
    thread_nums[i] = i;
    pthread_create(&threads[i], NULL, do_work, (void *) &thread_nums[i]);
   }
   ```
   - Each thread needs to be joined to the main thread/calling function
   
   ```
   for (i = 0; i < NTHREADS; i++) {
     pthread_join(threads[i], NULL);
   }
   ```
   - After each thread is done it needs to destroy itself (`pthread_exit(NULL);`), and at the end of the `parallel` block this must be called again (`pthread_exit(NULL);`).
   - The `atomic` block needs to take care of each thread using the mutex, like this
     `
     pthread_mutex_lock (&sum_mutex);
     sum = sum + local_sum;
     pthread_mutex_unlock (&sum_mutex);
     pthread_exit(NULL);
     `
   - The atomic block may also have to initialize the mutex (`pthread_mutex_init(&sum_mutex, NULL);`) (Unsure if this is possible or if it has to be initialized outside the block. Will experiment.)

**Comment by ThePhD** [comment]
@gabriellet I've covered all of these concerns in a heavily commented example. I'll push it before the meeting today.

**Comment by ThePhD** [comment]
There are 2 examples which show how to handle parallel code in its entirety. [parallel.lepix and parallel.c](https://github.com/ThePhD/lepix/blob/master/examples/parallel.c), and the 2d example [parallel_2d.lepix and parallel_2d.c](https://github.com/ThePhD/lepix/blob/master/examples/parallel_2d.c).

These two examples show what's necessary to mutex data, properly copy it, and use condition variables to signal work on threads. Note that this requires that we initialize the `lepix_thread_pool` before we enter, and destroy the `lepix_thread_pool` when we exit.

Each thread receives its own mutex, and the thread's work mutex is locked around data.

Parallel blocks will hold execution at the bottom of the block until all computation for each invocation is completed.

I do not know if nesting parallel blocks works (I don't think we should allow it?).

**Comment by ThePhD** [comment]
New syntax bikeshed at god-knows-when in the morning (from the GroupMe chat):
- `parallel( invocations = [ <expression>, <expression>, <expression>, ... ] ) { ... }`
- `parallel( invocations = <expression> ) { ... }` == `parallel( invocations = [<expression>] ) { ... }`
- `parallel () { ... };` and `parallel { ... }` == `parallel( invocations = thread_count );`

The idea is that `invocations` is the number of runs a thing can make. You can query the current invocation the parallel block is running with `lang.invocation_id[{index}]` for the line/patch/block id. Like all arrays, the first, second, third and fourth invocation ID can be retrieved with `lang.invocation_id.x`, `lang.invocation_id.y`, `lang.invocation_id.z` and `lang.invocation_id.w` respectively. (One could also use `lang.invocation_id.r`, `lang.invocation_id.g`, `lang.invocation_id.b`, and `lang.invocation_id.a`, but that's just because those names are aliases for [0], [1], [2] and [3], just like `.x .y .z .w`)

**Comment by ThePhD** [comment]
Support in the Lexer and Parser for the previous ideas bikeshed are now present. Now we just need to put this code into the #16 issue, since any C-Code we need to leverage in LePiX will be written as a C module and then linked in.

Code here: https://github.com/ThePhD/lepix/blob/master/examples/preamble/parallel_preamble.h
